# Generated by Django 2.0 on 2024-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_Intrusion_type_prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=300)),
                ('Location', models.CharField(max_length=300)),
                ('Latitude', models.CharField(max_length=300)),
                ('Longitude', models.CharField(max_length=300)),
                ('Avgpassengersperday', models.CharField(max_length=300)),
                ('Nooftrainspassing', models.CharField(max_length=300)),
                ('Nooftrainsstopping', models.CharField(max_length=300)),
                ('Noofplatforms', models.CharField(max_length=300)),
                ('Nooftracks', models.CharField(max_length=300)),
                ('Trainhaltingtime', models.CharField(max_length=300)),
                ('Avgtrainspeed', models.CharField(max_length=300)),
                ('Averageaccidentspermonth', models.CharField(max_length=300)),
                ('population', models.CharField(max_length=300)),
                ('PhysicalEnvironment', models.CharField(max_length=300)),
                ('DateTime', models.CharField(max_length=300)),
                ('admin_found', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
